program: script/sweep_nbfnet.py
method: grid
metric:
  goal: maximize
  name: valid_mrr
parameters:
  seed: 
    value: 1024

  dataset:
    parameters:
      class: 
        value: CoDExMedium
      root: 
        value: ~/projects/ULTRA/kg-datasets/

  model:
    parameters:
      class:
        value: NBFNetEig
      input_dim: 
        values: [32, 64, 128, 256]
      num_mlp_layer:
        values: [2,3,4]
      message_func:
        value: distmult
      aggregate_func: 
        value: sum
      activation: 
        value: no
      dependent: 
        value: no
      copy_weights: 
        value: yes
      freeze_relation_weights: 
        value: yes
      normalization: 
        value: sym
      k: 
        values: [4,8,16,32,64,128]
      atol: 
        values: [1.0e-6]
      niter: 
        values: [16,32,64,128] 
    
  task:
    parameters:
      name: 
        value: MultiGraphPretraining
      num_negative: 
        values: [32,64,128]
      strict_negative: 
        value: yes
      adversarial_temperature: 
        value: 1
      metric: 
        value: [mrr]

  optimizer:
    parameters:
      class: 
        value: AdamW
      lr: 
        values: [1.0e-4]

  train:
    parameters:
      gpus: 
        value: [0]
      batch_size: 
        value: 32
      num_epoch: 
        value: 50
      log_interval:
        value: 800
      batch_per_epoch: 
        value: 8000
      fast_test: 
        value: 500