output_dir: ~/projects/ULTRA/output

dataset:
  class: CoDExSmall
  root: ~/projects/ULTRA/kg-datasets/

model:
  class: NBFNet
  input_dim: 8
  hidden_dims: [8, 8, 8]
  message_func: ntn
  aggregate_func: sum
  short_cut: no
  layer_norm: no
  copy_weights: no
  freeze_relation_weights: yes
  dependent: no
  orthogonal: false
  
task:
  name: MultiGraphPretraining
  num_negative: 128
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10]

optimizer:
  class: AdamW
  lr: 5.0e-3

train:
  gpus: [0]
  batch_size: 32
  num_epoch: 25
  log_interval: 800
  batch_per_epoch: 8000
  fast_test: 500
  #logger: wandb